import typography from "@tailwindcss/typography";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          50: "hsl(var(--primary-50))",
          100: "hsl(var(--primary-100))",
          200: "hsl(var(--primary-200))",
          300: "hsl(var(--primary-300))",
          400: "hsl(var(--primary-400))",
          500: "hsl(var(--primary-500))",
          600: "hsl(var(--primary-600))",
          700: "hsl(var(--primary-700))",
          800: "hsl(var(--primary-800))",
          900: "hsl(var(--primary-900))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          bg: "hsl(var(--secondary-bg))",
          text: "hsl(var(--secondary-text))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        purple: {
          50: "hsl(var(--purple-50))",
          200: "hsl(var(--purple-200))",
          400: "hsl(var(--purple-400))",
          500: "hsl(var(--purple-500))",
          700: "hsl(var(--purple-700))",
          DEFAULT: "hsl(var(--purple-500))",
        },
        green: {
          50: "hsl(var(--green-50))",
          200: "hsl(var(--green-200))",
          400: "hsl(var(--green-400))",
          500: "hsl(var(--green-500))",
          700: "hsl(var(--green-700))",
          DEFAULT: "hsl(var(--green-500))",
        },
        blue: {
          50: "hsl(var(--blue-50))",
          200: "hsl(var(--blue-200))",
          400: "hsl(var(--blue-400))",
          500: "hsl(var(--blue-500))",
          700: "hsl(var(--blue-700))",
          DEFAULT: "hsl(var(--blue-500))",
        },
        rose: {
          50: "hsl(var(--rose-50))",
          200: "hsl(var(--rose-200))",
          400: "hsl(var(--rose-400))",
          500: "hsl(var(--rose-500))",
          700: "hsl(var(--rose-700))",
          DEFAULT: "hsl(var(--rose-500))",
        },
        amber: {
          50: "hsl(var(--amber-50))",
          200: "hsl(var(--amber-200))",
          400: "hsl(var(--amber-400))",
          500: "hsl(var(--amber-500))",
          700: "hsl(var(--amber-700))",
          DEFAULT: "hsl(var(--amber-500))",
        },
        slate: {
          500: "hsl(var(--slate-500))",
          600: "hsl(var(--slate-600))",
        },
        neutral: {
          0: "hsl(var(--neutral-000))",
          50: "hsl(var(--neutral-050))",
          100: "hsl(var(--neutral-100))",
          200: "hsl(var(--neutral-200))",
          300: "hsl(var(--neutral-300))",
          400: "hsl(var(--neutral-400))",
          500: "hsl(var(--neutral-500))",
          600: "hsl(var(--neutral-600))",
          700: "hsl(var(--neutral-700))",
          800: "hsl(var(--neutral-800))",
          900: "hsl(var(--neutral-900))",
          1000: "hsl(var(--neutral-1000))",
          ink: "hsl(var(--neutral-ink))",
        },
        fg: {
          1: "hsl(var(--fg-1))",
          2: "hsl(var(--fg-2))",
          3: "hsl(var(--fg-3))",
          4: "hsl(var(--fg-4))",
          inverse: "hsl(var(--fg-inverse))",
        },
        hero: {
          1: "hsl(var(--hero-1))",
          2: "hsl(var(--hero-2))",
          3: "hsl(var(--hero-3))",
          4: "hsl(var(--hero-4))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        highlight: "hsl(var(--highlight))",
      },
      borderRadius: {
        sm: "4px",
        md: "6px",
        lg: "var(--radius)",
        xl: "16px",
        "2xl": "60px",
        "3xl": "80px",
        pill: "9999px",
      },
      boxShadow: {
        card: "0 2px 6px 0 rgb(0 0 0 / 0.12), 0 0 4px 0 rgb(0 0 0 / 0.04)",
        sm: "0 1px 2px 0 rgb(0 0 0 / 0.08)",
        md: "0 2px 6px 0 rgb(0 0 0 / 0.12), 0 0 4px 0 rgb(0 0 0 / 0.04)",
        lg: "0 8px 24px 0 rgb(0 0 0 / 0.15)",
        tooltip: "0 2px 8px 0 rgb(0 0 0 / 0.15)",
      },
      fontFamily: {
        display: ['"Inter"', "-apple-system", "BlinkMacSystemFont", '"Segoe UI"', "sans-serif"],
        body: ['"Roboto"', '"Helvetica Neue"', "Arial", "sans-serif"],
        ui: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"SF Pro Text"',
          '"Inter"',
          '"Segoe UI"',
          "sans-serif",
        ],
        brand: ['"Montserrat"', '"Mont"', "sans-serif"],
        sans: ['"Roboto"', '"Helvetica Neue"', "Arial", "sans-serif"],
      },
    },
  },
  plugins: [typography],
};
